#!/usr/bin/env bash

# cron_rescheduler - reschedules the 'trash_mgr' cron.
#+ -> achieves this by executing the 'cron_scheduler' itself
#+ 		on each system reboot


# -- global variales -- #
errlog="/home/$USER/.trash/.errlog"						# abs path to err log
cron_scheduler="/home/$USER/trash_util/cron_scheduler"	# cron_scheduler path

# define and set cronjob
cron_job="@reboot "$cron_scheduler" 2>>$errlog"
(crontab -l -u "$USER" 2>>"$errlog"; echo "$cron_job") | crontab -
