#!/usr/bin/env bash

# cron_scheduler - schedules a cronjob for the current user
#+ -> the cronjob executes the 'trash_mgr' script 3 times daily
#+ -> the purpose is to permanently delete files as old as, or
#+ -> older than as defined in 'trash_mgr'
#+ -> errors are loged

# -- global variales -- #
errlog="$TRASH_UTIL_DIR/.errlog"
rmf="$TRASH_UTIL_DIR/rmf"

# define and set cronjob
cron_job="@reboot $TRASH_UTIL_DIR/cron_scheduler 2>>$errlog"
(crontab -l -u "$USER" 2>>"$errlog"; echo "$cron_job") | crontab -
