#!/usr/bin/env bash

# Installs the trash_util:
#+	1. Gets paths to all scripts
#+	2. Sets aliases for 'rm', 'rmf', and 'restore'
#+	3. Schedules cron tabs

# -- global variables -- #
set -e

trash_util_dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
IFS=' ' read -a trash_util_files <<< "rm rmf restore"
bash_rc="$HOME/.bashrc"
aliases=""


# get/set bash_profile file
if [[ ! -e "$bash_rc" ]]; then
	if [[ -e "$HOME/.bash_profile" ]]; then
		bash_rc="$HOME/.bash_profile"
	else
		# create bashrc
		touch "$bash_rc"
	fi
fi


# check if already installed and proceed iff otherwise
count="$(cat $bash_rc | grep -wc 'TRASH_UTIL_DIR' || true)"
if ((count > 0)); then
	echo "[ERROR]: trash_util already installed"
	exit
fi


# create all aliases
for file in ${trash_util_files[@]}; do
	aliases+="alias $file='$trash_util_dir/$file'\n"
done


# write aliases to bash_profile file
cat >> "$bash_rc" <<EOF

# ---- trash_util [start] ---- #
$(echo -e $aliases)
# set env variable
export TRASH_UTIL_DIR="$trash_util_dir"
# ----  trash_util [end]  ---- #
EOF

# schedule cron
#+ cron_scheduler
cron_exists="$(crontab -l | grep -wc "cron_scheduler" || true)"
if ((cron_exists == 0)); then
	"$trash_util_dir/cron_scheduler"
fi

#+ cron_rescheduler
cron_exists="$(crontab -l | grep -wc "cron_rescheduler" || true)"
if ((cron_exists == 0)); then
	"$trash_util_dir/cron_rescheduler"
fi

echo "[SUCCESS]: installation complete"
