#!/usr/bin/env bash

# Installs the trash_util:
#+	1. Gets paths to all scripts
#+	2. Sets aliases for 'rm', 'rmf', and 'restore'
#+	3. Schedules cron tabs

# -- global variables -- #
set -e

trash_util_dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
IFS=' ' read -a trash_util_files <<< "rm rmf restore"
bash_rc="$HOME/.bashrc"
aliases=""

# check if already installed and proceed iff otherwise
if [[ ! -z "$TRASH_UTIL_DIR" ]]; then
	echo "trash_util already installed"
	exit
fi


# create all aliases
for file in ${trash_util_files[@]}; do
	aliases+="alias $file='$trash_util_dir/$file'\n"
done

# get/set bash_profile file
if [[ ! -e "$bash_rc" ]]; then
	if [[ -e "$HOME/.bash_profile" ]]; then
		bash_rc="$HOME/.bash_profile"
	else
		# create bashrc
		touch "$bash_rc"
	fi
fi

# write aliases to bash_profile file
cat >> "$bash_rc" <<EOF

# ---- trash_util [start] ---- #
$(echo -e $aliases)
# set env variable
export TRASH_UTIL_DIR="$trash_util_dir"
# ----  trash_util [end]  ---- #
EOF

# schedule crons
"$trash_util_dir/cron_scheduler"
"$trash_util_dir/cron_rescheduler"
