#!/usr/bin/env bash

# Installs the trash_util:
#+	1. Gets paths to all scripts
#+	2. Sets aliases for 'rm', 'rmf', and 'restore'
#+	3. Schedules cron tabs

# -- global variables -- #
trash_util_dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
IFS=' ' read -a trash_util_files <<< "rm rmf restore"
aliases=""
bash_rc="$HOME/.bashrc"

# create all aliases
for file in ${trash_util_files[@]}; do
	aliases+="alias $file='$trash_util_dir/$file'\n"
done

# get/set bash_profile file
if [[ ! -e "$bash_rc" ]]; then
	if [[ -e "$HOME/.bash_profile" ]]; then
		bash_rc="$HOME/.bash_profile"
	else
		# create bashrc
		touch "$bash_rc"
	fi
fi

# write aliases to bash_profile file
cat > "tmp" <<EOF
# ---- trash_util aliases[START] ---- #
$(echo -e $aliases)
# ----  trash_util aliases[END]  ---- #
EOF