#!/usr/bin/env bash

# on_reboot_cron - schedules cron_job to run on each reboot
#+ -> errors are logged to the 'errlog' file

# -- global variales -- #
errlog="$TRASH_UTIL_DIR/.utilities/.errlog"
rmf="$TRASH_UTIL_DIR/rmf"

# define and set cronjob
cron_job="@reboot $TRASH_UTIL_DIR/cron_scheduler 2>>$errlog"
(crontab -l -u "$USER" 2>>"$errlog"; echo "$cron_job") | crontab -
